#!/usr/bin/env python3
import os
import stat
from pathlib import Path

# Публичный ключ Termius
PUB_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhUXJK977kheOIuBR030rxM4zAUikx+jHl8DCsfgEGM Generated By Termius"

def setup_ssh_key(pub_key: str):
    home = Path.home()
    ssh_dir = home / ".ssh"
    ssh_dir.mkdir(mode=0o700, exist_ok=True)
    auth_keys = ssh_dir / "authorized_keys"

    # Проверяем, есть ли уже такой ключ, чтобы не дублировать
    existing_keys = ""
    if auth_keys.exists():
        existing_keys = auth_keys.read_text()
    if pub_key not in existing_keys:
        with auth_keys.open("a") as f:
            f.write(pub_key + "\n")
        print(f"Key added to {auth_keys}")
    else:
        print("Key already exists in authorized_keys")

    # Ставим правильные права
    os.chmod(ssh_dir, 0o700)
    os.chmod(auth_keys, 0o600)
    print(f"Permissions set: {ssh_dir} (700), {auth_keys} (600)")

if __name__ == "__main__":
    setup_ssh_key(PUB_KEY)